### ISSUE TITLE
Deprecate LifecycleRoutes.active_lifecycle

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-workflow-client#106]
It's just a duplicate of LifecycleRoutes.lifecycle and is a legacy of the old workflow service.

**Comment by jcoyne** [comment]
There is a significant difference.  `active_lifecycle` sets the `active-only` parameter which the workflow server acts on here: https://github.com/sul-dlss/workflow-server-rails/blob/42a43177cdda28e218598f5b1334193897bbfeaf/app/controllers/workflows_controller.rb#L14
