### ISSUE TITLE
throw a unique error for a missing workflow 

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-workflow-client#139]
PR https://github.com/sul-dlss/preservation_catalog/pull/1247 addresses creating missing workflow for pres audit errors but it's matching on the string in the error message for a Dor::WorkflowException.

We should raise a unique exception and be able to trap the exception class instead.

So this would involve
- [x] adding the unique `Dor::MissingWorkflowException` error (subclass of Dor::WorkflowException) and throwing it when WF doesn't exist in dor-workflow-client: ~https://github.com/sul-dlss/dor-workflow-client/pull/138~
- [x] cut a new release of dor-workflow-client
- [x] bump dor-workflow-client in prescat and update prescat code to trap for Dor::MissingWorkflow instead of Dor::WorkflowException with a particular string: https://github.com/sul-dlss/preservation_catalog/pull/1260

**Comment by mjgiarlo** [comment]
Fixed by https://github.com/sul-dlss/preservation_catalog/pull/1260
